package org.apache.ruta.server;

import static org.apache.ruta.server.Utils.list;
import static org.apache.ruta.server.Utils.map;

import java.util.List;
import java.util.Map;

import org.apache.uima.analysis_engine.AnalysisEngineProcessException;
import org.apache.uima.cas.CASException;
import org.apache.uima.resource.ResourceInitializationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * 
 * RESTful controller for RUTA server. Exposes the service via /annotate GET
 * method.
 * 
 * @author renaud@apache.org
 */
@Controller
@EnableAutoConfiguration
@ComponentScan
public class RutaController {

	private RutaEngine rutaEngine;

	/**
	 * Comma separated list of types. Only these types are displayed (with the
	 * css)
	 */
	@Value("${ruta.types}")
	String typesString;
	final List<String> colors = list("lightgreen", "green", "mediumpurple",
			"yellow", "cyan", "salmon", "tan", "blue", "brown", "lightblue",
			"lightred", "orange", "lightgray");

	@Autowired
	public void setRutaEngine(RutaEngine rutaEngine) {
		this.rutaEngine = rutaEngine;
	}

	@RequestMapping("/annotate")
	@ResponseBody
	Map<String, Object> recommend(@RequestParam String text)
			throws AnalysisEngineProcessException,
			ResourceInitializationException, CASException {

		Map<String, Object> response = map();
		response.put("text", text);
		response.put("annotations", rutaEngine.process(text));
		return response;
	}

	/** To generate the css for highlighting types */
	@RequestMapping(value = "/types.css", produces = "text/css")
	@ResponseBody
	String css() throws AnalysisEngineProcessException,
			ResourceInitializationException, CASException {
		StringBuilder css = new StringBuilder();
		css.append("/* automatically generated by RutaController, based on the value of 'ruta.types' config parameter*/");
		int i = 0;
		for (String type : list(typesString.split(":"))) {
			css.append("." + type + "{color:black;background:"
					+ colors.get(i++ % colors.size()) + ";}\n");
		}
		return css.toString();
	}

	public static void main(String[] args) throws Exception {
		SpringApplication.run(RutaController.class, args);
	}
}